#!/bin/bash
#SBATCH --job-name=travelling_salesman        # Job name
#SBATCH --ntasks=1                       # Run on a single CPU
#SBATCH --cpus-per-task=40                  # ...with four cores
#SBATCH --mem=4gb                        # Job memory request
#SBATCH --time=00:20:00                  # Time limit hrs:min:sec
#SBATCH --output=travelling_salesman.log        # Standard output and error log
#SBATCH --partition=teach         # Project account
 
echo My working directory is `pwd`
echo Running job on host:
echo -e '\t'`hostname` at `date`
echo
 
module load lang/Python/3.8.2-GCCcore-9.3.0

# pip install -r requirements.txt
  
python testing.py
  
echo
echo Job completed at `date`